webtalk_init -webtalk_dir D:\\Projects\\zedboard_cortex_m1\\m1_for_arty_a7.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-02-06 00:48:25" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "nphjts3kcjgau4q8eq45p6d26a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.512 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1549400526087" -context "sdk\\\\bsp/1549400526087"
webtalk_add_data -client sdk -key hwid -value "1549031876555" -context "sdk\\\\bsp/1549400526087"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1549400526087"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1549400526087"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1549400526087"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1549410505023"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1549410505023"
webtalk_transmit -clientid 1856972607 -regid "" -xml D:\\Projects\\zedboard_cortex_m1\\m1_for_arty_a7.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Projects\\zedboard_cortex_m1\\m1_for_arty_a7.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Projects\\zedboard_cortex_m1\\m1_for_arty_a7.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
